
		<!-- Footer starts -->
		<footer>
		  <div class="container">
			<div class="row">
			  <div class="col-md-12">

					<div class="row">
					  <div class="col-md-4">
						<div class="widget">
						  <h5>Contato</h5>
						  <hr />
						  <p>Entre em contato conosco para que possamos entender seus problemas e solucionar-los.</p>
						  <hr />
						  <i class="fa fa-home"></i> &nbsp; R. Rodolfo Belz, 154 - Jardim Lar <br>
						  <i class="fa fa-none"></i> &nbsp; São Paulo, SP, 05639-010
						  <hr />
						  <i class="fa fa-phone"></i> &nbsp; +55 11 96626-9225
						  <hr />
						  <i class="fa fa-envelope-o"></i> &nbsp; <a href="mailto:engenheiro.claudio@gmail.com">contato@cproengenharia.com.br</a>
						  <hr />
							<div class="social">
							  <a href="#"><i class="fa fa-facebook facebook"></i></a>
							  <a href="#"><i class="fa fa-twitter twitter"></i></a>
							  <a href="#"><i class="fa fa-linkedin linkedin"></i></a>
							  <a href="#"><i class="fa fa-google-plus google-plus"></i></a>
							</div>
						</div>
					  </div>

					  <div class="col-md-4">
						<div class="widget">
						  <h5>Sobre</h5>
						  <hr />
						  <p>A CPRO – Consultoria e Projetos de Engenharia Ltda. é uma empresa jovem no ramo de projetos de construção civil. Fundada em 2013 por Claudio Alves de Souza, engenheiro civil formado em 2005 pela Escola Politécnica da USP.</p>
						  <p>A empresa foi criada para a elaboração de projetos de estruturas de concreto e aço. Atualmente a CPRO atua nas áreas de projetos de estruturas de concreto, estruturas de aço, fundações e hidráulica predial.</p>
						</div>
					  </div>

					  <div class="col-md-4">
						<div class="widget">
						  <h5>Principais Links</h5>
						  <hr />
						  <div class="one-col">
							<div class="col-left">
							  <ul>
								<li><a href="/">Home</a></li>
								<li><a href="/cases">Cases</a></li>
								<li><a href="/servicos">Serviços</a></li>
								<li><a href="/clientes">Clientes</a></li>
								<li><a href="/fale-conosco">Orçamento</a></li>
								<li><a href="/mapa-site">Mapa do Site</a></li>
							  </ul>
							</div>
							<div class="col-right">
							  <ul>
							  	<li><a href="/sobre/empresa">Empresa</a></li>
								<li><a href="/sobre/profissionais">Profissionais</a></li>
								<li><a href="/empresa">Depoimentos</a></li>
								<li><a href="/publicacoes">Publicações</a></li>
								<li><a href="/fale-conosco">Fale Conosco</a></li>
							  </ul>
							</div>
							<div class="clearfix"></div>
						  </div>
						</div>
					  </div>

					</div>

					<hr />

					<!-- Copyright info -->
					<p class="copy center">Copyright &copy; 2015 - CPRO Engenharia LTDA. | Todos os direitos reservados</p>
			  </div>
			</div>
		  <div class="clearfix"></div>
		  </div>
		</footer>

		<!-- Footer ends -->

		<!-- Scroll to top -->
		<span class="totop"><a href="#"><i class="fa fa-chevron-up"></i></a></span>

		<!-- Javascript files -->
		<!-- jQuery -->
		<script src="<?php echo URL; ?>Content/js/jquery.js"></script>
		<!-- Bootstrap JS -->
		<script src="<?php echo URL; ?>Content/js/bootstrap.min.js"></script>
		<!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
		<script src="<?php echo URL; ?>Content/js/jquery.themepunch.plugins.min.js"></script>
		<script src="<?php echo URL; ?>Content/js/jquery.themepunch.revolution.min.js"></script>
		<!-- Isotope, Pretty Photo JS -->
		<script src="<?php echo URL; ?>Content/js/jquery.isotope.js"></script>
		<script src="<?php echo URL; ?>Content/js/jquery.prettyPhoto.js"></script>
		<!-- Filter for support page -->
		<script src="<?php echo URL; ?>Content/js/filter.js"></script>
		<!-- Flex slider -->
		<script src="<?php echo URL; ?>Content/js/jquery.flexslider-min.js"></script>
		<!-- Parallax Slider -->
		<script src="<?php echo URL; ?>Content/js/jquery.cslider.js"></script>
		<!-- Parallax slider extra -->
		<script src="<?php echo URL; ?>Content/js/modernizr.custom.28468.js"></script>
		<!-- Owl Carousel -->
		<script src="<?php echo URL; ?>Content/js/owl.carousel.min.js"></script>
		<!-- Respond JS for IE8 -->
		<script src="<?php echo URL; ?>Content/js/respond.min.js"></script>
		<!-- HTML5 Support for IE -->
		<script src="<?php echo URL; ?>Content/js/html5shiv.js"></script>
		<!-- Custom JS -->
		<script src="<?php echo URL; ?>Content/js/custom.js"></script>
		<!-- This Page Script -->
		<script>
			// Revolution Slider
			var revapi;
			jQuery(document).ready(function() {
				   revapi = jQuery('.tp-banner').revolution(
					{
						delay: 9000,
						startwidth: 1170,
						startheight: 450,
						hideThumbs: 200,
						shadow: 0,
						navigationType: "none",
						hideThumbsOnMobile: "on",
						hideArrowsOnMobile: "on",
						hideThumbsUnderResoluition: 0,
						touchenabled: "on",
						fullWidth: "on"
					});
			});

		</script>
	</body>
</html>