<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<!-- Title here -->
		<title>CPRO Engenharia</title>
		<!-- Description, Keywords and Author -->
		<meta name="description" content="Projetos de construção civil realizando os sonhos de seus clientes.">
		<meta name="keywords" content="Projetos em Engenharia, Engenharia Civil, Contrução, Engenheiro, Serviços de Contrução, Estruturas, Projetos Arquitetura, Consultoria em TI">
		<meta name="author" content="CPRO Consultoria e Projetos de Engenharia LTDA">
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<!-- Styles -->
		<!-- Bootstrap CSS -->
		<link href="Content/css/bootstrap.min.css" rel="stylesheet">
		<!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
		<link href="Content/css/settings.css" rel="stylesheet" media="screen" />
		<!-- Pretty Photo -->
		<link href="Content/css/prettyPhoto.css" rel="stylesheet">
		<!-- Flex slider -->
		<link href="Content/css/flexslider.css" rel="stylesheet">
		<!-- Parallax slider -->
		<link href="Content/css/slider.css" rel="stylesheet">
		<!-- Owl Carousel -->
		<link href="Content/css/owl.carousel.css" rel="stylesheet"> 
		<!-- Font awesome CSS -->
		<link href="Content/css/font-awesome.min.css" rel="stylesheet">		
		<!-- Custom CSS -->
		<link href="Content/css/style.css" rel="stylesheet">
		<!-- Stylesheet for Color -->
		<link href="Content/css/blue.css" rel="stylesheet">
	
		<!-- Favicon -->
		<link href="Content/img/favicon/favicon.png" rel="shortcut icon">
	</head>
	
	<body>
	
		<!-- Header starts -->
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-3">
					  <!-- Logo. Use class "color" to add color to the text. -->
					  <div class="logo">
						<h1><a href="index"><span class="color bold">CPRO</span>Engenharia</a></h1>
						<p class="meta center">Tornando possível projetos exclusivos.</p>
					  </div>
					</div>
					<div class="col-md-8 col-sm-9">
						<!-- Navigation -->
						<div class="navbar bs-docs-nav" role="banner">
							<div class="navbar-header">
								<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>

								</button>
							</div>
						   
							<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
								<ul class="nav navbar-nav navbar-right">
								  <li>
									<a href="index">Home</a>
								  </li>
								  <li class="dropdown">
									 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sobre Nós <b class="caret"></b></a>
									 <ul class="dropdown-menu">
									   <li><a href="sobre/empresa">Empresa</a></li>
									   <li><a href="sobre/profissionais">Profissionais</a></li>
									   <li><a href="sobre/depoimentos">Depoimentos</a></li>
									 </ul>
								  </li>                   
								  
								  <li><a href="servicos">Serviços</a></li>
								  <li><a href="portifolio">Portifólio</a></li>
								  <li><a href="clientes">Clientes</a></li>
								  <li><a href="publicacoes">Publicações</a></li>
								  <li><a href="fale-conosco">Fale Conosco</a></li>
								</ul>
							</nav>
						</div>
						<!--/ Navigation end -->
					</div>
				</div>
			</div>
		</header>
		<!-- Seperator -->
		<div class="sep"></div>
		<!--/ Header ends -->
