
<!-- Page heading starts -->

<div class="page-head">
  <div class="container">
	<div class="row">
	  <div class="col-md-12">
		<h2>Mapa do Site</h2>
		<h4>Encontre aqui os principais conteúdos do site</h4>
	  </div>
	</div>
  </div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h5>Digite a sessão para filtrar</h5>
				<div id="form"></div>
				<hr />

				<div class="clearfix"></div>
				<!-- Lists -->
				<ul id="slist">

					<?php
						$value = 1;

						foreach (array(1,2,3,4,5,6) as $value)
						{
							echo '<li>';
							   echo '<a href="#">Título da Sessão ' . $value . '</a>';
							   echo '<p>TEXTO.</p>';
							echo '</li>';

							$value = $value + 1;
						}

					?>
				</ul>
			</div>

			<div class="col-md-4">
				<div class="scontact well">
					<h4>Contato</h4>
					<p>Entre em contato conosco e solicite um orçamento.</p>
					<p><i class="fa fa-phone"></i> Phone<strong>:</strong> +55 11 96626-9225</p>
					<p><i class="fa fa-envelope-o"></i> <strong>Email:</strong> contato@cproengenharia.com.br</p>
					<p><i class="fa fa-home"></i> <strong>Address:</strong> R Rodolfo Belz, 220 - São Paulo, SP, CEP 05639-010 </p>

					<!-- Button -->
					<div class="button rp">
						<a href="/fale-conosco">Fale Conosco</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

<!-- Page content ends -->
