
<!-- Page heading starts -->

<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Serviços</h2>
        <h4>Confira os serviços exclusivos que a CPRO oferece à você.</h4>
      </div>
    </div>
  </div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="content">
  <div class="container">


    <div class="row rp">
     <div class="col-md-12">
       <!-- Section title with font awesome icon -->
       <h3 class="title"><i class="fa fa-cloud"></i> Engenharia Civil</h3>
     </div>
   </div>

   <div class="row">
     <div class="col-md-4 col-sm-4">
       <!-- Service title -->
       <h5>Serviço 1</h5>
       <!-- Service para -->
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div>
     <div class="col-md-4 col-sm-4">
       <h5>Serviço 2</h5>
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div>
     <div class="col-md-4 col-sm-4">
       <h5>Serviço 3</h5>
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div> 

   </div>

   <div class="row rp">
     <div class="col-md-4 col-sm-4">
       <!-- Service title -->
       <h5>Serviço 4</h5>
       <!-- Service para -->
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div>
     <div class="col-md-4 col-sm-4">
       <h5>Serviço 5</h5>
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div>
     <div class="col-md-4 col-sm-4">
       <h5>Serviço 6</h5>
       <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
     </div> 

   </div>
   <hr />

   <div class="row rp">
    <div class="col-md-12">
      <h3 class="title"><i class="fa fa-envelope-o"></i> Mobile Services</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-sm-4">
      <h5>Mobile Apps</h5>
      <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
    </div>
    <div class="col-md-4 col-sm-4">
      <h5>Apple Apps</h5>
      <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
    </div>
    <div class="col-md-4 col-sm-4">
      <h5>iPad Apps</h5>
      <p>Suspesse potenti. Morbi ac felis nec mauris imperdiet fermentum. Aenean sodales augue ac lacus hendrerit sed rhoncus erat hendrerit. Vivamus vel ultricies elit. Nulla vitae cursus leo. </p>
    </div>       
  </div>

</div>
</div>

<!-- Page content ends -->
