

<?php

$v_params = $this->getParams();
$st_name = $v_params['Nome'];
$a_social = array(
					'Facebook' => 'https://pt-br.facebook.com/fasfelipe',
					'Linkedin' => 'http://www.linkedin.com.br',
					'Twitter' => 'https://www.twitter.com'
				);
$st_titulo = 'Faculdade de Engenharia Civil';
$st_instituicao = 'Universidade de São Paulo - USP';
$st_skills = array('HTML5', 'HTML5', 'CSS3', 'jQuery', 'WordPress', 'Twitter Bootstrap', 'Photoshop');

?>

<!-- Page heading starts -->

<div class="page-head">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Currículo</h2>
				<h4>Saiba um pouco mais sobre os profissionais envolvidos em seu projeto.</h4>
			</div>
		</div>
	</div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="content resume">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- Name with the job detail-->
				<h2><?php echo $st_name; ?> <span class="rsmall"><span class="color">@</span> CIO</span></h2>
					<?php echo '<p>' . $st_name . '</p>'; ?>

				<div class="bor"></div>

				<div class="clearfix"></div>

				<div class="rblock">
					<div class="row">
						<div class="col-md-3">
							<h4>Sobre</h4>
						</div>
						<div class="col-md-9">
							<div class="rinfo">
								<?php
									echo '<h5>' . $st_name . '</h5>';
									echo '<div class="rmeta">Professional Web Designer</div>';
									echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci. Duis a risus sed dolor placerat semper quis in urna. Nam risus magna, fringilla sit amet blandit viverra, dignissim eget est. Ut <strong>commodo ullamcorper risus nec</strong> mattis. </p>';

									if (!empty($a_social))
									{
										echo '<div class="social">';

										foreach ($a_social as $key => $value)
										{
											echo '<a href="' . $value . '"  target="_blank"><i class="fa fa-' . strtolower($key) . ' ' . strtolower($key) . '"></i></a>';

										}

										echo '</div>';
									}
								?>
							</div>
						</div>
					</div>
				</div>
				<!-- Education -->
				<div class="rblock">
					<div class="row">
						<div class="col-md-3">
							<h4>Educação</h4>
						</div>
						<div class="col-md-9">
							<div class="rinfo">
								<?php
									echo '<h5>' . $st_titulo . '</h5>';
									echo '<div class="rmeta">' . $st_instituicao . '</div>';
									echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci.</p>';

									echo '<hr>';

									echo '<h5>' . $st_titulo . '</h5>';
									echo '<div class="rmeta">' . $st_instituicao . '</div>';
									echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci.</p>';
								?>
							</div>
						</div>
					</div>
				</div>

				<!-- Experience -->
				<div class="rblock">
					<div class="row">
						<div class="col-md-3">
							<h4>Experiencia Profissional</h4>
						</div>
						<div class="col-md-9">
							<div class="rinfo">

								<?php
									echo '<h5>Google India</h5>';
									echo '<div class="rmeta">' . $st_instituicao . '</div>';
									echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci.</p>';

									echo '<hr>';

									echo '<h5>' . $st_titulo . '</h5>';
									echo '<div class="rmeta">' . $st_instituicao . '</div>';
									echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci.</p>';
								?>
							</div>
						</div>
					</div>
				</div>
				<!-- Skills -->
				<div class="rblock">
					<div class="row">
						<div class="col-md-3">
							<h4>Habilidades</h4>
						</div>
						<div class="col-md-9">
							<div class="rinfo">
								<!-- Class "rskills" is important -->
								<div class="rskills">
									<?php
										foreach ($st_skills as $value)
										{
											echo '<span>' . $value . '</span> ';
										}
									?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Page content ends -->
