
<!-- Page heading starts -->

<div class="page-head">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <h2>Sobre Nós</h2>
            <h4>Conheça mais sobre o histórico da empresa e seus profissionais.</h4>
         </div>
      </div>
   </div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="container">
   <div class="rp">
      <div class="row">
         <div class="col-md-6">
            <h4>CPRO Engenharia</h4> 
            <p>A CPRO – Consultoria e projetos de engenharia Ltda. é uma empresa jovem no ramo de projetos de construção civil. Fundada em 2013 por Claudio Alves de Souza, engenheiro civil formado em 2005 pela Escola Politécnica da USP, a CPRO, inicialmente, foi criada para a elaboração de projetos de estruturas de concreto e aço. Atualmente a CPRO atua nas áreas de projetos de estruturas de concreto, estruturas de aço, fundações e hidráulica predial.</p>
            <p>Apesar de nova no mercado os profissionais responsáveis pelo levantamento do escopo, coordenação e execução do projeto técnico são experientes no mercado trabalhando em grandes projetos como a contrução da Linha 4 Metro de São Paulo entre outros.</p>

         </div>

         <div class="col-md-6">
               <h4>Missão</h4> 
               <p>Atendimento aos anseios de seus clientes buscando a elaboração de projetos econômicos e em conformidade com as exigências preconizadas nas normas técnicas vigentes.</p>

            <div class="rp">
               <h4>Valores</h4> 
               <li>Excelência</li>
               <li>Profissionalismo</li>
               <li>Transparência</li>
            </div>
         </div>
      </div>

   </div>
   <hr />
</div>

<div class="container">
   <div class="rp">




      <div class="row">


         <div class="col-md-6">
            <h4>O que a CPRO oferce?</h4>
            <p>Aliquam consequat, purus vitae auctor ullamcorper, sem velit convallis quam, a pharetra justo nunc et mauris. Vivamus diam diam, fermentum sed dapibus eget, egestas sed eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <div class="aserv-list">
               <div class="col-left">

                  <!-- Service #1 -->
                  <div class="aserv">
                     <!-- Font awesome icon -->
                     <div class="aserv-img">
                        <i class="fa fa-gift"></i>
                     </div>
                     <!-- Detail -->
                     <div class="aserv-details">
                        Fertum <span class="color">sed dapius</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-globe"></i>
                     </div>
                     <div class="aserv-details">
                        Egestas <span class="color">sed daibus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-truck"></i>
                     </div>
                     <div class="aserv-details">
                        Daibus <span class="color">sed dapbus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-filter"></i>
                     </div>
                     <div class="aserv-details">
                        Utteus <span class="color">sed dapius</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>                                    

               </div>
               <div class="col-right">
                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-tag"></i>
                     </div>
                     <div class="aserv-details">
                        Conetur <span class="color">sed daus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-flask"></i>
                     </div>
                     <div class="aserv-details">
                        Aliuam <span class="color">sed dapibus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-fire"></i>
                     </div>
                     <div class="aserv-details">
                        Vivus <span class="color">sed dapibus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-thumb-tack"></i>
                     </div>
                     <div class="aserv-details">
                        Fertum <span class="color">sed daibus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>                                     
               </div>    
               <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>   
            <hr />
         </div> 

         <div class="col-md-6">
            <h4>Por que escolher a CPRO Engenharia?</h4>
            <p>Aliquam consequat, purus vitae auctor ullamcorper, sem velit convallis quam, a pharetra justo nunc et mauris. Vivamus diam diam, fermentum sed dapibus eget, egestas sed eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <div class="aserv-list">
               <div class="col-left">

                  <!-- Service #1 -->
                  <div class="aserv">
                     <!-- Font awesome icon -->
                     <div class="aserv-img">
                        <i class="fa fa-gift"></i>
                     </div>
                     <!-- Detail -->
                     <div class="aserv-details">
                        Ferum <span class="color">sed dapus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-globe"></i>
                     </div>
                     <div class="aserv-details">
                        Egestas <span class="color">sed dapus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-truck"></i>
                     </div>
                     <div class="aserv-details">
                        Dabus <span class="color">sed dapbus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-filter"></i>
                     </div>
                     <div class="aserv-details">
                        Utmpus <span class="color">sed dabus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>                                    

               </div>
               <div class="col-right">
                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-tag"></i>
                     </div>
                     <div class="aserv-details">
                        Coetur <span class="color">sed dbus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-flask"></i>
                     </div>
                     <div class="aserv-details">
                        Aliuam <span class="color">sed dapus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-fire"></i>
                     </div>
                     <div class="aserv-details">
                        Vivamus <span class="color">sed dapbus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>

                  <div class="aserv">
                     <div class="aserv-img">
                        <i class="fa fa-thumb-tack"></i>
                     </div>
                     <div class="aserv-details">
                        Fermm <span class="color">sed dabus</span>
                     </div>
                     <div class="clearfix"></div>
                  </div>                                     
               </div>    
               <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>     
            <hr />
         </div> 


      </div>
   </div>
</div>

<div class="content about-one">
   <div class="container">
      <div class="row">
         <div class="col-md-4 col-sm-4">
            <div class="ceo">
               <!-- Staff name with designation. Designation should be enclosed inside <span> tag. -->
               <h4 class="title">Claudio Souza <span class="color">CEO</span></h4>
               <!-- Staff Photo -->
               <a href="/sobre/curriculo/claudio-souza"><img src="<?php echo URL; ?>Content/img/photos/cas.jpg" alt="Claudio A. Souza" /></a>
               <!-- Social media links -->
               <div class="padd social">
                  <a href="#"><i class="fa fa-facebook facebook"></i></a> 
                  <a href="#"><i class="fa fa-twitter twitter"></i></a> 
                  <a href="#"><i class="fa fa-linkedin linkedin"></i></a> 
                  <a href="#"><i class="fa fa-google-plus google-plus"></i></a>
               </div>
               <!-- Small para -->
               <p>Donec at lectus id diam feugiat dictum et eget mi. Nam mauris orci, varius non imperdiet luctus, facilisis mattis mi. Nullam turpis odio, porttitor eu aliquam eu, adipiscing vitae velit. </p>
            </div>
            <!--<div class="bor"></div>-->
         </div>
         <div class="col-md-4 col-sm-4">
            <div class="ceo">
               <!-- Staff name with designation. Designation should be enclosed inside <span> tag. -->
               <h4 class="title">Felipe Souza <span class="color">CFO</span></h4>
               <!-- Staff photo -->
               <a href="/sobre/curriculo/felipe-souza"><img src="<?php echo URL; ?>Content/img/photos/Felipe.png" alt="Felipe A. Souza" /></a>
               <!-- Social media links -->
               <div class="padd social">
                  <a href="#"><i class="fa fa-facebook facebook"></i></a> 
                  <a href="#"><i class="fa fa-twitter twitter"></i></a> 
                  <a href="#"><i class="fa fa-linkedin linkedin"></i></a> 
                  <a href="#"><i class="fa fa-google-plus google-plus"></i></a>
               </div>
               <!-- Para -->
               <p>Ut quam leo, venenatis sed pulvinar nec, pretium sit amet purus. Pellentesque gravida commodo pulvinar. Ut elementum vehicula lorem, sed imperdiet nisi iaculis et. Ut ut ante rhoncus diam. </p>
            </div>
         </div>

         <div class="col-md-4 col-sm-4">
            <div class="ceo">
               <!-- Staff name with designation. Designation should be enclosed inside <span> tag. -->
               <h4 class="title">Babu <span class="color">CTO</span></h4>
               <!-- Staff photo -->
               <a href="/sobre/curriculo/flavia-mieko"><img src="<?php echo URL; ?>Content/img/photos/fmk.jpg" alt="" /></a>
               <!-- Social media links -->
               <div class="padd social">
                  <a href="#"><i class="fa fa-facebook facebook"></i></a> 
                  <a href="#"><i class="fa fa-twitter twitter"></i></a> 
                  <a href="#"><i class="fa fa-linkedin linkedin"></i></a> 
                  <a href="#"><i class="fa fa-google-plus google-plus"></i></a>
               </div>
               <!-- Para -->
               <p>Ut quam leo, venenatis sed pulvinar nec, pretium sit amet purus. Pellentesque gravida commodo pulvinar. Ut elementum vehicula lorem, sed imperdiet nisi iaculis et. Ut ut ante rhoncus diam. </p>
            </div>
         </div>            

         <div class="clearfix"></div>
      </div>
   </div>
</div>

<!-- Page content ends -->


<div class="container">

  <div class="clearfix"></div>

  <div class="row">
     <div class="col-md-12">
      <div class="bor"></div>
      <h4>Depoimentos</h4>
   </div>
</div>

<!-- Testimonials style 2 -->
<div class="row">
   <div class="col-md-4 col-sm-4">
    <div class="testi-two">
      <!-- Testimonial #1 -->
      <div class="test">
         Praesent at tellus porttitor nisl porttitor sagittis. Mauris in massa ligula, a tempor nulla. Ut tempus interdum mauris vel vehicula. Nulla ullamcorper tortor commodo in sagittis est accumsan.
      </div>
      <div class="test-arrow"></div>
      <!-- Author name -->
      <div class="tauth"><i class="fa fa-user"></i> Ashok, <span class="color">Google</span></div>
   </div>
   <hr>
</div>

<div class="col-md-4 col-sm-4">
 <div class="testi-two">
   <!-- Testimonial #2 -->
   <div class="test">
      Praesent at tellus porttitor nisl porttitor sagittis. Mauris in massa ligula, a tempor nulla. Ut tempus interdum mauris vel vehicula. Nulla ullamcorper tortor commodo in sagittis est accumsan.
   </div>
   <div class="test-arrow"></div>
   <div class="tauth"><i class="fa fa-user"></i> Ashok, <span class="color">Google</span></div>
</div>
<hr>
</div>

<div class="col-md-4 col-sm-4">
 <div class="testi-two">
   <!-- Testimonial #3 -->
   <div class="test">
      Praesent at tellus porttitor nisl porttitor sagittis. Mauris in massa ligula, a tempor nulla. Ut tempus interdum mauris vel vehicula. Nulla ullamcorper tortor commodo in sagittis est accumsan.
   </div>
   <div class="test-arrow"></div>
   <div class="tauth"><i class="fa fa-user"></i> Ashok, <span class="color">Google</span></div>
</div>
<hr>
</div>
</div>
</div>
