
<!-- Page heading starts -->

<div class="page-head">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Fale Conosco</h2>
				<h4>Entre em contato conosco para dúvidas e informações sobre os nossos serviços.</h4>
			</div>
		</div>
	</div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="content contact-two">
	<div class="container">
		<div class="row">

			<div class="col-md-6">
				<!-- Contact form -->
				<h4 class="title">Preencha o formulário</h4>

				<form role="form">
					<div class="form-group">
						<label for="name">Nome Completo</label>
						<input type="text" class="form-control" id="name" placeholder="Digite seu nome completo">
					</div>

					<div class="form-group">
						<label for="exampleInputEmail1">E-mail</label>
						<input type="email" class="form-control" id="exampleInputEmail1" placeholder="Digite o seu e-mail">
					</div>

					<div class="form-group">
						<label for="exampleInputEmail1">Mensagem</label>
						<textarea class="form-control" rows="5"></textarea>
					</div>

					<div class="form-group">
						<label for="optin">
							Gostaria de receber nossas comunicações
							<br>
							<input type="radio" name="optin" value="sim">Sim
							<input type="radio" name="optin" value="não">Não
						</label>
					</div>

					<button type="submit" class="btn btn-default">Enviar</button>
					<button type="reset" class="btn btn-default">Limpar</button>
				</form>

				<hr />

				<div class="center">
					<!-- Social media icons -->
					<strong>Visite a gente nas redes sociais</strong>

					<div class="social">
						<a href="#"><i class="fa fa-facebook facebook"></i></a>
						<a href="#"><i class="fa fa-twitter twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin linkedin"></i></a>
						<a href="#"><i class="fa fa-google-plus google-plus"></i></a>
						<a href="#"><i class="fa fa-pinterest pinterest"></i></a>
					</div>
				</div>
				<hr />
			</div>

			<div class="col-md-6">
				<h4 class="title">Localização</h4>
				<!-- Google maps -->
				<div class="gmap">
					<!-- Google Maps. Replace the below iframe with your Google Maps embed code -->
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1827.9336822549187!2d-46.742403299999985!3d-23.609089299999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce56a3f3aac383%3A0xf34df84befb460c0!2sR.+Rodolfo+Belz%2C+220+-+Jardim+Lar+Sao+Paulo%2C+S%C3%A3o+Paulo+-+SP%2C+05639-010!5e0!3m2!1spt-BR!2sbr!4v1425950516202" width="400" height="200" frameborder="0" style="border:0"></iframe>
				</div>

				<hr />
				<!-- Address section -->
				<h4 class="title">Endereço</h4>
				<div class="address">
					<address>
					<!-- Company name -->
					<strong>CPRO CONSULTORIA E PROJETOS DE ENGENHARIA</strong><br>
					<!-- Address -->
					R Rodolfo Belz, 220 - Jd. Lar São Paulo<br>
					São Paulo, SP, CEP 05639-010<br>
					<!-- Phone number -->
					<abbr title="TIM">Tel:</abbr> +55 11 96626-9225.
					</address>

					<address>
					<!-- Name -->
					<strong>Claudio Alves de Souza</strong><br>
					<!-- Email -->
					<a href="mailto:engenheiro.claudio@gmail.com">contato@cproengenharia.com.br</a>
					</address>
				</div>
			</div>

		</div>
	</div>
</div>

<!-- Page content ends -->
