<!-- Page content starts -->

<div class="content error-page">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6">  
      <div class="big-text">500</div>
        <hr />
      </div>
      <div class="col-md-7 col-md-offset-1 col-sm-6">
        <h2>Oops<span class="color">!!!</span></h2>
        <h4>Servidor com problemas</h4>
        <hr />
        <!-- Some links -->
        <div class="horizontal-links">
          <h5>Navegue em nossas principais categorias</h5>
          <a href="index">Home</a> <a href="sobre/empresa">Empresa</a> <a href="clientes">Clientes</a> <a href="fale-conosco">Fale Conosco</a> <a href="portifolio">Portifólio</a>
        </div>
        <hr />
      </div>

    </div>
  </div>
</div>

<!-- Page content ends -->