<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Manutenção</title>
        <link href="./Everhour   Maintenance_files/css" rel="stylesheet" type="text/css">

        <style type="text/css">
            body {
                background: #ec6a38;
                -webkit-font-smoothing: antialiased;
                -webkit-animation: colour 20s linear infinite;
                -moz-animation: colour 20s linear infinite;
                font-family: 'Ubuntu', sans-serif;
                font-weight: 400;
                position: relative;
                min-width: 960px;
                min-height: 100%;
                padding: 0;
                padding-bottom: 150px;
                margin: 0;
                font-size: 13px;
                line-height: 1.4;
                color: #252523;
                word-wrap: break-word
            }

            .err-layout {
                padding-top: 40px;
                margin: 0 auto;
                width: 50em
            }

            .err-logo {
                background: url('Content/img/clients/6.png') no-repeat;
                width: 115px;
                height: 40px;
                margin-bottom: 50px
            }

            .err-header {
                font-size: 60px;
                color: #fff;
                margin-bottom: 20px
            }

            .err-description {
                font-size: 30px;
                color: #671c07;
                line-height: 45px;
                margin-bottom: 60px
            }

            .err-links {
                font-size: 18px;
                color: #fff;
            }

            .err-links a {
                text-decoration: underline;
                color: #fff;
                cursor: pointer
            }

            @-webkit-keyframes colour {
                0% {
                    background: #ec6a38
                }
                40% {
                    background: #ec4038
                }
                80% {
                    background: #ec9138
                }
                100% {
                    background: #ec6a38
                }
            }

            @-moz-keyframes colour {
                0% {
                    background: #ec6a38
                }
                40% {
                    background: #ec4038
                }
                80% {
                    background: #ec9138
                }
                100% {
                    background: #ec6a38
                }
            }
        </style>
        <style type="text/css"></style>
    </head>

    <body>
        <div class="err-layout">
            <h1 class="err-logo"></h1>
            <h1 class="err-header">Manutenção</h1>
            <p class="err-description">O site esta em manutenção preventiva. Voltaremos num piscar de olhos, obrigado pela paciência.</p>

            <p class="err-links">Enquanto isto veja as novidades em nossa página do <a href="https://www.facebook.com/">Facebook</a></p>
        </div>
    </body>
</html>