
<!-- Page heading starts -->

<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Publicações</h2>
        <h4>Publicações técnicas a respeito de assuntos em foco na Engenharia Civil</h4>
      </div>
    </div>
  </div>
</div>

<!-- Page Heading ends -->

<!-- Page content starts -->

<div class="content blog">
  <div class="container">
    <div class="row">
      <div class="col-md-8">

                           <div class="posts">

                              <!-- Each posts should be enclosed inside "entry" class" -->
                              <!-- Post one -->
                              <div class="entry">
                                <!-- Title -->
                                 <h2><a href="/publicacoes/a2015/estruturas-metalicas">Sed justo scelerisque ut consectetur</a></h2>

                                 <!-- Meta details. Date, author, category and comment -->
                                 <div class="meta">
                                    <i class="fa fa-calendar"></i> 26-2-2012 <i class="fa fa-user"></i> <a href="sobre/curriculo/claudio-souza">Claudio</a> <span class="pull-right"><i class="fa fa-comment"></i> <a href="#">2 Comments</a></span>
                                 </div>

                                 <!-- Thumbnail -->
                                 <div class="bthumb">
                                    <a href="/publicacoes/a2015/estruturas-metalicas"><img src="<?php echo URL; ?>Content/img/photos/l1.jpg" alt="" class="img-responsive"/></a>
                                 </div>

                                 <!-- Content -->
                                 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci. Duis a risus sed dolor placerat semper quis in urna. Nam risus magna, fringilla sit amet blandit viverra, dignissim eget est. Ut <strong>commodo ullamcorper risus nec</strong> mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. Nulla facilisi. Aenean at massa leo. Vestibulum in varius arcu.</p>
                                 <!-- Read more -->
                                 <div class="button"><a href="/publicacoes/a2015/estruturas-metalicas">Continue a leitura</a></div>
                              </div>

                              <!-- Post 2 -->
                              <div class="entry">
                                 <h2><a href="/publicacoes/a2015/concreto-armado">Ut commodo ullamcorper risus nec mattis</a></h2>

                                 <!-- Meta details -->
                                 <div class="meta">
                                    <i class="fa fa-calendar"></i> 26-2-2012 <i class="fa fa-user"></i> <a href="sobre/curriculo/claudio-souza">Claudio</a> <span class="pull-right"><i class="fa fa-comment"></i> <a href="#">2 Comments</a></span>
                                 </div>

                                 <!-- Thumbnail -->
                                 <div class="bthumb">
                                    <a href="/publicacoes/a2015/concreto-armado"><img src="Content/img/photos/l2.jpg" alt="" class="img-responsive"/></a>
                                 </div>

                                 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate eros nec odio egestas in dictum nisi vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porttitor luctus imperdiet. <a href="#">Praesent ultricies</a> enim ac ipsum aliquet pellentesque. Nullam justo nunc, dignissim at convallis posuere, sodales eu orci. Duis a risus sed dolor placerat semper quis in urna. Nam risus magna, fringilla sit amet blandit viverra, dignissim eget est. Ut <strong>commodo ullamcorper risus nec</strong> mattis. Fusce imperdiet ornare dignissim. Donec aliquet convallis tortor, et placerat quam posuere posuere. Morbi tincidunt posuere turpis eu laoreet. Nulla facilisi. Aenean at massa leo. Vestibulum in varius arcu.</p>
                                 <div class="button"><a href="/publicacoes/a2015/concreto-armado">Continue a leitura</a></div>
                              </div>

                              <!-- Pagination -->
                              <div class="paging">
                                 <span class='current'>1</span>
                                 <a href='#'>2</a>
                                 <span class="dots">&hellip;</span>
                                 <a href='#'>6</a>
                                 <a href="#">Next</a>
                              </div>

                              <div class="clearfix"></div>

                           </div>
                        </div>
                        <div class="col-md-4">
                          <!-- Sidebar -->
                           <div class="sidebar">

                              <!-- Widget #1 -->
                              <div class="widget">
                                 <h4>Busca</h4>
                                 <form class="form-inline" role="form">
                                   <div class="form-group">
                                     <input type="text" class="form-control" id="search" placeholder="Type Something...">
                                   </div>
                                   <button type="submit" class="btn btn-default">Procurar</button>
                                 </form>
                              </div>

                              <div class="widget">
                                 <h4>Tags</h4>
                                 <div class="posts">
                                 <div class="tags">
                                  <a href="#">Estruturas</a>
                                  <a href="#">Concreto</a>
                                  <a href="#">Treliças</a>
                                 </div>
                                 </div>

                               </div>

                              <div class="widget">
                                 <h4>Publicações Recentes</h4>
                                 <ul>
                                 <li>Etiam adipiscing posuere justo, nec iaculis justo dictum non</li>
                                 <li>Cras tincidunt mi non arcu hendrerit eleifend</li>
                                 <li>Aenean ullamcorper justo tincidunt justo aliquet et lobortis diam faucibus</li>
                                 <li>Maecenas hendrerit neque id ante dictum mattis</li>
                                 <li>Vivamus non neque lacus, et cursus tortor</li>
                                 </ul>
                              </div>

                              <div class="widget">
                                 <h4>Sobre o Autor</h4>
                                 <p><strong>Claudio Alves de Souza</strong> um dos fundadores da empresa e Engenheiro Civil formado em 2005 pela <em>Escola Politécnica da USP</em> com mestrado na área de Estruturas.</p>
                              </div>

                           </div>
                        </div>
    </div>
  </div>
</div>

<!-- Page content ends -->
